[package]
name = "lehmer"
description = "Convert between permutation vectors, Lehmer codes and decimals."
version = "1.0.0"
authors = ["Chris Patuzzo <chris@patuzzo.co.uk>"]
license = "MIT"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "lehmer_bench"
harness = false
